# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01

    working_directory: ~/project
    
    steps:
      - checkout
      - run: 
          name: "Prepare environment"
          command: mv ./src/Test.env.development ./src/.env.development && mv ./Test.env ./.env
      - run: 
          name: "Start database"
          command: docker-compose run --service-ports database
      - run: 
          name: "Run tests"
          command: cd ./src/ && npm run test

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  test:
    jobs:
      - build